site_name: Dokumentation eGov-Campus

site_url:  http://egov-leitfaden.readthedocs.io/
site_author: Ina Stein
site_description:
# Repository
#repo_name:
#repo_url:
#edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 eGov-Campus

# Configuration

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

docs_dir: docs
theme:
  name: material
  custom_dir: overrides
  language: de
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Encode Sans
  palette:
   - scheme: eGov




nav:
  - Home: 'index.md'
  - Kursdesign:
    - kursdesign/index.md
    - Roadmap: 'kursdesign/roadmap.md'
    - Zielgruppen: 'kursdesign/target.md'
    - Lernziele: 'kursdesign/lernziel.md'
    - Kursstruktur: 'kursdesign/struktur.md'
    - Formate: 'kursdesign/format.md'
    - Übungen: 'kursdesign/uebung.md'
  - Plattform:
    - lms/index.md
    - Neues Video einpflegen: 'lms/video.md'
    - Quiz anlegen: 'lms/quiz.md'
    - Text einfügen: 'lms/text-schreiben.md'
    - Externes Video einbetten: 'lms/video-extern.md'
    - YouTube-Video einbetten: 'lms/youtube.md'
    - Section erstellen: 'lms/section.md'
    - Peer Assessment anlegen: 'lms/Peer-assessment.md'
    - Diskussionsforum: 'lms/diskussionsforum.md'
    - Lernräume anlegen: 'lms/lernraeume.md'
  - FAQs: 'faq.md'
  - Checklisten: 'chklist.md'
  - Feedback: 'feedback.md'
  - Über den eGov-Campus: 'about.md'
